backend:
  device: real
  optimization: 0
  provider: aer
  shots: 4000
circuit:
  ansatz: generic
  beta:
    pi_sigma: 2
  encoding: angular
  generic:
    num_gates: 10
    type: G1
  num_qubits: 5
  show_template: false
data:
  deterministic_seed: true
  num_labels: 1
  num_samples: 143
  optimal_num_samples: true
  path: null
  pick_random: all
  sequence_length: 15
  vocabulary: 32
  washout_percentage: 100
  washout_period: 5
embedding:
  dimension: 3
  normalize: null
  sigma: 0.5
  transfer_path: null
  type: random
gen:
  show_circuits: false
measurement:
  basis: Z
  batch_size: 300
  eps: 0.2
  mixing: 1
  num_states: 32
  outcome: counts
  protocol: hybrid
  save: false
  sigma: 5
  skip_washout: false
seed: 0
training:
  batch_size: 2
  epoch: 100
  rate: 1e-2
  save_weights: false
  scale: 40
  summary: false
  threshold: 0.5
